spring.application.name=api-gateway
server.port=8080

auth.jwt.secret=QWJjZEVmZ0hpSmtMbW5PcFFyU3RVdld4WXpBQkNERUZHSElKS0xtbm9w


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*), /api/auth/$\{segment}

spring.cloud.gateway.routes[1].id=post-category-tag-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/posts/**,/categories/**,/tags/**,/admin/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/(?<segment>.*), /api/$\{segment}

spring.cloud.gateway.routes[2].id=comment-like-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/comments/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/comments(?<segment>/?.*), /api/comments$\{segment}

spring.cloud.gateway.routes[3].id=media-service
spring.cloud.gateway.routes[3].uri=lb://media-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/media/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/media(?<segment>/?.*), /api/media$\{segment}

spring.cloud.gateway.routes[4].id=newsletter-subscription-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/newsletter/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/newsletter/(?<segment>.*), /api/newsletter/$\{segment}

spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://notification-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/notifications/(?<segment>.*), /api/notifications/$\{segment}

spring.cloud.gateway.routes[6].id=auth-oauth-bridge
spring.cloud.gateway.routes[6].uri=lb://auth-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/oauth2/**,/login/**


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
