spring.application.name=comment-like-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/scriptly_comments?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=RIDsriv9683@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

comments.edit-window-minutes=30
comments.moderation-required=false
services.post.base-url=http://localhost:8082
services.notification.base-url=http://localhost:8086
services.auth.base-url=http://localhost:8081

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
